apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: adi-dev
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: adihaimsohn/toppicks-auth
        ports:
          - containerPort: 3000
        env: 
          - name: MONGO_URI
            value: 'mongodb://auth-mongo-srv:27017/auth'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: toppicks

--- 

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: adi-dev
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP 
    port: 3000
    targetPort: 3000


