apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  namespace: adi-dev
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: adihaimsohn/toppicks-products
        ports:
          - containerPort: 3000
        env: 
          - name: MONGO_URI
            value: 'mongodb://products-mongo-srv:27017/products'
          # - name: JWT_KEY
          #   valueFrom:
          #     secretKeyRef:
          #       name: jwt-secret
          #       key: JWT_KEY

--- 

apiVersion: v1
kind: Service
metadata:
  name: products-srv
  namespace: adi-dev
spec:
  selector:
    app: products
  ports:
  - name: products
    protocol: TCP 
    port: 3000
    targetPort: 3000


