name: tests-user-ratings

on:
  pull_request:
    paths:
      - 'user-ratings/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd user-ratings && npm install && npm run test:ci
