name: tests-products

on:
  pull_request:
    paths:
      - 'products/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [windows-latest, ubuntu-latest, macos-latest]
        # os: [windows-latest]
    
    steps:
      - uses: actions/checkout@v2
      - run: node -v && cd products && ls src/__mocks__ && npm install && npm run test:ci
