name: tests-brands

on:
  pull_request:
    paths:
      - 'brands/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd brands && npm install && npm run test:ci
