name: tests-products

on:
  pull_request:
    paths:
      - 'products/**'

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - run: node -v && cd products && ls src/__mocks__ && npm install && npm run test:ci
